FROM python:3-slim
RUN useradd -ms /bin/bash vamserver
EXPOSE 8888/tcp
ADD --chown=vamserver ./VAMMultiplayerTCPServerless.py /home/vamserver
ADD --chown=vamserver ./VamMultiplayerTCP.py /home/vamserver
USER vamserver
WORKDIR /home/vamserver
ENTRYPOINT [ "python3", "./VAMMultiplayerTCPServerless.py"]